services:
  mongo:
    image: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=114514
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=114514
      - ME_CONFIG_MONGODB_SERVER=mongo
volumes:
  mongo: